### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by muziing** [eglinuxer/study_cmake#1]
发现一处疑似错别字：

[第 006 讲：CMake 变量之缓存变量](https://github.com/eglinuxer/study_cmake/blob/main/doc/006_cmake_var_cache.md) 中 BOOL 小节，
“但是我建议统一使用大小” -> “但是我建议统一使用大写”

非常感谢作者的课程分享，让我这个初学者能够快速入门，受益匪浅。无意吹毛求疵，本着帮助作者将文档更加完美的态度，以读者身份提交此 issue。

**Comment by eglinuxer** [comment]
感谢！

**Comment by eglinuxer** [comment]
已经更正。
