### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by muziing** [eglinuxer/study_cmake#2]
[第 013 讲：CMake 流程控制之 for 循环](https://github.com/eglinuxer/study_cmake/blob/main/doc/013_cmake_foreach.md)

“这个时候 CMake 的 foreach() 命令就派上*可*用场” -> “这个时候 CMake 的 foreach() 命令就可以派上用场”

“每一次循环，loopVar 都*讲*从 arg1 arg2 ... 中取出一个值” -> “每一次循环，loopVar 都将从 arg1 arg2 ... 中取出一个值”

**Comment by eglinuxer** [comment]
已经更正，非常感谢！下次可直接提 pull request。
